# Generated by Django 4.2.6 on 2023-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_teacher_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='details',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teachers',
        ),
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.CharField(default='Default description', max_length=500, null=True),
        ),
    ]
